name: Create Issues from Parts
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  split-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Issues from Parts
        run: |
          for i in $(ls Parts)
          do
            .github/scripts/createIssue.sh $i
          done
